"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Lang = "en" | "ru";

const STORAGE_KEY = "pg-lang";

/**
 * Flat, dotted-key message catalogue. Every user-visible string in the UI chrome lives here so the
 * whole site can switch between English and Russian at runtime. Per-finding prose (titles /
 * descriptions / recommendations) is generated by the Java analyzer and is therefore English; the
 * *structured* labels around it (severity, category, verdict, sandbox status, behaviour type) are
 * translated below.
 */
type Dict = Record<string, string>;

const en: Dict = {
  // ── Navbar ──────────────────────────────────────────────────────────────
  "nav.scanner": "Scanner",
  "nav.demo": "Demo report",
  "nav.pipeline": "Pipeline",
  "nav.language": "Language",

  // ── Footer ──────────────────────────────────────────────────────────────
  "footer.tagline": "PluginGuard — risk-based static analysis. Not a guarantee of safety.",
  "footer.meta": "static bytecode analysis · isolated sandbox",

  // ── Home / hero ─────────────────────────────────────────────────────────
  "home.kicker": "minecraft plugin security",
  "home.title.a": "Know what a plugin",
  "home.title.b": "really does",
  "home.title.c": "before you run it.",
  "home.lead.a": "Upload a",
  "home.lead.b":
    "and get a forensic report — dangerous calls, network indicators, obfuscation scoring and",
  "home.lead.c": " validation. Static analysis plus an isolated sandbox run.",
  "home.lead.tags": "runtime.exec · webhooks · classloading · obfuscation · plugin.yml",

  "home.pipeline.kicker": "analysis pipeline",
  "home.pipeline.title": "Six passes over every JAR",
  "home.pipeline.note":
    "Each upload runs the full pipeline — no pass is skipped, no result is cached from another file.",

  "home.sample.kicker": "sample verdict",
  "home.sample.title": "Reports you can act on",
  "home.sample.body":
    "Every finding names the exact class and method behind it, what the risk is, and what to check — backed by network, filesystem and dependency summaries.",
  "home.sample.cta": "Open the demo report",
  "home.sample.f1": "External Discord webhook",
  "home.sample.f1.loc": "WebhookClient#sendModerationLog",
  "home.sample.f2": "Reflection used to access server internals",
  "home.sample.f2.loc": "NMSResolver#resolve",
  "home.sample.f3": "Makes HTTP requests",
  "home.sample.f3.loc": "UpdateChecker#check",

  // ── Feature grid ────────────────────────────────────────────────────────
  "feature.bytecode": "Bytecode",
  "feature.bytecode.p1": "Runtime.exec",
  "feature.bytecode.p2": "Class loading",
  "feature.bytecode.p3": "Reflection",
  "feature.network": "Network",
  "feature.network.p1": "Webhooks",
  "feature.network.p2": "IPs & URLs",
  "feature.network.p3": "Sockets",
  "feature.deps": "Dependencies",
  "feature.deps.p1": "Bundled libs",
  "feature.deps.p2": "SBOM",
  "feature.deps.p3": "Shaded jars",
  "feature.obf": "Obfuscation",
  "feature.obf.p1": "Base64 blobs",
  "feature.obf.p2": "Class names",
  "feature.obf.p3": "Reflection density",
  "feature.yml": "plugin.yml",
  "feature.yml.p1": "Commands",
  "feature.yml.p2": "Permissions",
  "feature.yml.p3": "Main class",
  "feature.prov": "Provenance",
  "feature.prov.p1": "SHA-256",
  "feature.prov.p2": "Source check",
  "feature.prov.p3": "Signatures",

  // ── Dropzone ────────────────────────────────────────────────────────────
  "dropzone.badExt": "Please choose a plugin/mod .jar or a resource/data pack .zip.",
  "dropzone.tooLarge": "File is too large ({size}). Max is 50 MB.",
  "dropzone.failed": "Analysis failed.",
  "dropzone.scanning": "Scanning bytecode…",
  "dropzone.title.a": "Drop a",
  "dropzone.title.or": "or",
  "dropzone.title.b": "to scan it",
  "dropzone.kinds": "plugin · mod · resource / data pack · up to 50 MB",
  "dropzone.choose": "Choose file",
  "dropzone.isolated": "analyzed in isolation — nothing runs on your server",

  // ── Report view ─────────────────────────────────────────────────────────
  "report.sha": "sha-256",
  "report.copySha": "Copy SHA-256",
  "report.platform": "platform",
  "report.size": "size",
  "report.mcApi": "mc api",
  "report.mainClass": "main class",
  "report.classesMethods": "classes / methods",
  "report.analyzedIn": "analyzed in",
  "report.descriptor": "descriptor",
  "report.name": "name",
  "report.version": "version",
  "report.authors": "authors",
  "report.commands": "commands",
  "report.permissions": "permissions",
  "report.dependencies": "dependencies",
  "report.network": "network",
  "report.filesystem": "filesystem",
  "report.obfuscation": "obfuscation",
  "report.engineNotes": "engine notes",
  "report.noneDeclared": "None declared",
  "report.none": "None",
  "report.noDescriptor": "No descriptor found.",
  "report.noNetwork": "No network indicators found.",
  "report.noFilesystem": "No notable filesystem paths.",
  "report.noDeps": "No bundled dependencies detected.",
  "report.obfNote": "Higher means more obfuscated. Not malicious on its own.",
  "report.findings": "findings — {n}",
  "report.expandAll": "Expand all",
  "report.collapseAll": "Collapse all",
  "report.all": "All",
  "report.noFindings": "No findings.",
  "report.footer.static": "static analysis — the plugin was never executed",
  "report.footer.sandbox": "static analysis + isolated sandbox run",
  "report.footer.line": "analyzed in {ms} ms · engine v{v} · {mode}",
  "report.gaugeLabel": "safety / 100",
  "report.outOf": "/ 100",

  // ── Finding card ────────────────────────────────────────────────────────
  "finding.location": "location",
  "finding.evidence": "evidence",
  "finding.correlated": "correlated",
  "finding.in": "in",
  "finding.recommendation": "Recommendation —",
  "finding.pts": "−{n} pts",

  // ── Sandbox panel ───────────────────────────────────────────────────────
  "sandbox.title": "dynamic sandbox",
  "sandbox.intro":
    "The plugin was executed in an isolated, network-blocked container and its real behavior recorded. This catches reflection-built or decoded actions that static analysis cannot see.",
  "sandbox.running": "Running the plugin in the sandbox…",
  "sandbox.runningSuffix": "This page refreshes automatically.",
  "sandbox.inactive": "No dynamic analysis was performed.",
  "sandbox.clean":
    "No dangerous runtime behavior was observed in the code paths that were triggered.",
  "sandbox.newMissed": "New — static missed it",
  "sandbox.confirms": "Confirms static",
  "sandbox.blocked": "Blocked",
  "sandbox.trail": "Behavior trail — {n} event{s}",
  "sandbox.blockedLower": "blocked",
  "sandbox.caveatsSummary": "What a sandbox can and cannot prove",
  "sandbox.recommendation": "Recommendation —",

  // ── Authenticity (online provenance) panel ──────────────────────────────
  "provenance.title": "authenticity",
  "provenance.intro":
    "This file was compared online against the genuine release published on official sources (Modrinth, Hangar, GitHub). It catches backdoored copies of popular plugins handed out on untrusted sites.",
  "provenance.running": "Checking official sources…",
  "provenance.runningSuffix": "This page refreshes automatically.",
  "provenanceStatus.DISABLED": "disabled",
  "provenanceStatus.PENDING": "queued",
  "provenanceStatus.RUNNING": "checking",
  "provenanceStatus.VERIFIED": "authentic",
  "provenanceStatus.TAMPERED": "tampered",
  "provenanceStatus.NOT_FOUND": "not found",
  "provenanceStatus.UNVERIFIED": "unverified",
  "provenanceStatus.SKIPPED": "skipped",
  "provenanceStatus.FAILED": "failed",
  "provenance.verifiedTitle": "Genuine official release",
  "provenance.verifiedBody":
    "These bytes are identical to the official release — this is the authentic build, not a modified copy.",
  "provenance.tamperedTitle": "Does NOT match the official release",
  "provenance.tamperedBody":
    "This file claims to be {name} {version} but its bytes differ from the official release on {source}. A modified copy of a known plugin is a strong sign of a backdoor.",
  "provenance.notFoundTitle": "Could not be verified",
  "provenance.notFoundBody":
    "{name} was not found on any queried official source, so its authenticity could not be confirmed. Absence of a match is not proof of tampering.",
  "provenance.unverifiedBody":
    "No plugin name/version or source link was found to verify this file against.",
  "provenance.project": "Project",
  "provenance.version": "Version",
  "provenance.source": "Source",
  "provenance.officialFile": "Official file",
  "provenance.openProject": "Open on {source}",
  "provenance.diffTitle": "Difference from the official build",
  "provenance.diffCounts": "official {o} classes · this file {u} classes",
  "provenance.diffAdded": "Added — not in the official build ({n})",
  "provenance.diffModified": "Modified ({n})",
  "provenance.diffRemoved": "Removed ({n})",
  "provenance.diffInjected": "injected",
  "provenance.diffTruncated": "…and more (list truncated)",
  "provenance.sources": "Sources checked",
  "provenance.caveatsSummary": "What this check can and cannot prove",

  // ── Report client (loading / error) ─────────────────────────────────────
  "reportClient.loading": "Loading report…",
  "reportClient.unavailable": "Report unavailable",
  "reportClient.loadError": "Could not load this report.",
  "reportClient.expire": "Reports are kept in memory and expire when the analyzer restarts.",
  "reportClient.scanCta": "Scan a plugin",
  "api.unreachable": "Could not reach the analyzer service. Is it running on {url}?",

  // ── Verdicts ────────────────────────────────────────────────────────────
  "verdict.MINIMAL_RISK": "Minimal Risk",
  "verdict.LOW_RISK": "Low Risk",
  "verdict.MEDIUM_RISK": "Medium Risk",
  "verdict.HIGH_RISK": "High Risk",
  "verdict.CRITICAL_RISK": "Critical Risk",

  // ── Severities ──────────────────────────────────────────────────────────
  "severity.CRITICAL": "Critical",
  "severity.HIGH": "High",
  "severity.MEDIUM": "Medium",
  "severity.LOW": "Low",
  "severity.INFO": "Info",
  "severityShort.CRITICAL": "Crit",
  "severityShort.HIGH": "High",
  "severityShort.MEDIUM": "Med",
  "severityShort.LOW": "Low",
  "severityShort.INFO": "Info",

  // ── Categories ──────────────────────────────────────────────────────────
  "category.STRUCTURE": "Structure",
  "category.PLUGIN_YML": "plugin.yml",
  "category.NETWORK": "Network",
  "category.PROCESS": "Process",
  "category.CLASS_LOADING": "Class loading",
  "category.NATIVE": "Native code",
  "category.FILESYSTEM": "Filesystem",
  "category.CRYPTO": "Crypto",
  "category.REFLECTION": "Reflection",
  "category.SCRIPTING": "Scripting",
  "category.DESERIALIZATION": "Deserialization",
  "category.SYSTEM": "JVM control",
  "category.OBFUSCATION": "Obfuscation",
  "category.STRING_IOC": "Indicators",
  "category.SUPPLY_CHAIN": "Supply chain",
  "category.COMBO": "Correlated",
  "category.MINECRAFT": "Minecraft API",
  "category.MALWARE_SIGNATURE": "Known malware",
  "category.RESOURCE_PACK": "Resource pack",
  "category.DATA_PACK": "Data pack",
  "category.PROVENANCE": "Provenance",

  // ── Sandbox status ──────────────────────────────────────────────────────
  "sandboxStatus.DISABLED": "Disabled",
  "sandboxStatus.PENDING": "Queued",
  "sandboxStatus.RUNNING": "Running",
  "sandboxStatus.COMPLETED": "Completed",
  "sandboxStatus.SKIPPED": "Skipped",
  "sandboxStatus.UNAVAILABLE": "Unavailable",
  "sandboxStatus.FAILED": "Failed",

  // ── Behaviour types ─────────────────────────────────────────────────────
  "behavior.PROCESS_EXEC": "Process execution",
  "behavior.DEFINE_CLASS": "Runtime class definition",
  "behavior.LOAD_LIBRARY": "Native library load",
  "behavior.JNDI_LOOKUP": "JNDI lookup",
  "behavior.SECURITY_MANAGER": "Sandbox-escape attempt",
  "behavior.DESERIALIZE": "Deserialization",
  "behavior.NETWORK_CONNECT": "Outbound connection",
  "behavior.NETWORK_LISTEN": "Listening socket",
  "behavior.SCRIPTING": "Script evaluation",
  "behavior.DNS_RESOLVE": "DNS resolution",
  "behavior.FILE_WRITE": "Filesystem write",
  "behavior.FILE_READ": "Filesystem read",
  "behavior.REFLECTION": "Reflection",
  "behavior.SET_PROPERTY": "System property change",
  "behavior.ENV_READ": "Environment read",
  "behavior.OUTPUT": "Output",
  "behavior.LIFECYCLE": "Lifecycle",
  "behavior.ERROR": "Harness error",
};

const ru: Dict = {
  // ── Navbar ──────────────────────────────────────────────────────────────
  "nav.scanner": "Сканер",
  "nav.demo": "Демо-отчёт",
  "nav.pipeline": "Конвейер",
  "nav.language": "Язык",

  // ── Footer ──────────────────────────────────────────────────────────────
  "footer.tagline":
    "PluginGuard — статический анализ на основе рисков. Не является гарантией безопасности.",
  "footer.meta": "статический анализ байткода · изолированная песочница",

  // ── Home / hero ─────────────────────────────────────────────────────────
  "home.kicker": "безопасность плагинов minecraft",
  "home.title.a": "Узнайте, что плагин",
  "home.title.b": "делает на самом деле",
  "home.title.c": "до того, как запустить его.",
  "home.lead.a": "Загрузите",
  "home.lead.b":
    "и получите экспертный отчёт — опасные вызовы, сетевые индикаторы, оценку обфускации и проверку",
  "home.lead.c": ". Статический анализ плюс запуск в изолированной песочнице.",
  "home.lead.tags": "runtime.exec · вебхуки · загрузка классов · обфускация · plugin.yml",

  "home.pipeline.kicker": "конвейер анализа",
  "home.pipeline.title": "Шесть проходов по каждому JAR",
  "home.pipeline.note":
    "Каждая загрузка проходит весь конвейер — ни один проход не пропускается, ни один результат не берётся из другого файла.",

  "home.sample.kicker": "пример вердикта",
  "home.sample.title": "Отчёты, по которым можно действовать",
  "home.sample.body":
    "Каждая находка указывает точный класс и метод, в чём риск и что проверить — вместе со сводками по сети, файловой системе и зависимостям.",
  "home.sample.cta": "Открыть демо-отчёт",
  "home.sample.f1": "Внешний вебхук Discord",
  "home.sample.f1.loc": "WebhookClient#sendModerationLog",
  "home.sample.f2": "Рефлексия для доступа к внутренностям сервера",
  "home.sample.f2.loc": "NMSResolver#resolve",
  "home.sample.f3": "Выполняет HTTP-запросы",
  "home.sample.f3.loc": "UpdateChecker#check",

  // ── Feature grid ────────────────────────────────────────────────────────
  "feature.bytecode": "Байткод",
  "feature.bytecode.p1": "Runtime.exec",
  "feature.bytecode.p2": "Загрузка классов",
  "feature.bytecode.p3": "Рефлексия",
  "feature.network": "Сеть",
  "feature.network.p1": "Вебхуки",
  "feature.network.p2": "IP и URL",
  "feature.network.p3": "Сокеты",
  "feature.deps": "Зависимости",
  "feature.deps.p1": "Встроенные библиотеки",
  "feature.deps.p2": "SBOM",
  "feature.deps.p3": "Shaded-jar'ы",
  "feature.obf": "Обфускация",
  "feature.obf.p1": "Base64-блобы",
  "feature.obf.p2": "Имена классов",
  "feature.obf.p3": "Плотность рефлексии",
  "feature.yml": "plugin.yml",
  "feature.yml.p1": "Команды",
  "feature.yml.p2": "Права",
  "feature.yml.p3": "Главный класс",
  "feature.prov": "Происхождение",
  "feature.prov.p1": "SHA-256",
  "feature.prov.p2": "Проверка исходников",
  "feature.prov.p3": "Подписи",

  // ── Dropzone ────────────────────────────────────────────────────────────
  "dropzone.badExt": "Выберите .jar плагина/мода или .zip ресурс-/дата-пака.",
  "dropzone.tooLarge": "Файл слишком большой ({size}). Максимум 50 МБ.",
  "dropzone.failed": "Анализ не удался.",
  "dropzone.scanning": "Сканирование байткода…",
  "dropzone.title.a": "Перетащите",
  "dropzone.title.or": "или",
  "dropzone.title.b": "для проверки",
  "dropzone.kinds": "плагин · мод · ресурс- / дата-пак · до 50 МБ",
  "dropzone.choose": "Выбрать файл",
  "dropzone.isolated": "анализ изолирован — на вашем сервере ничего не запускается",

  // ── Report view ─────────────────────────────────────────────────────────
  "report.sha": "sha-256",
  "report.copySha": "Скопировать SHA-256",
  "report.platform": "платформа",
  "report.size": "размер",
  "report.mcApi": "mc api",
  "report.mainClass": "главный класс",
  "report.classesMethods": "классы / методы",
  "report.analyzedIn": "анализ занял",
  "report.descriptor": "дескриптор",
  "report.name": "имя",
  "report.version": "версия",
  "report.authors": "авторы",
  "report.commands": "команды",
  "report.permissions": "права",
  "report.dependencies": "зависимости",
  "report.network": "сеть",
  "report.filesystem": "файловая система",
  "report.obfuscation": "обфускация",
  "report.engineNotes": "заметки движка",
  "report.noneDeclared": "Не указаны",
  "report.none": "Нет",
  "report.noDescriptor": "Дескриптор не найден.",
  "report.noNetwork": "Сетевых индикаторов не найдено.",
  "report.noFilesystem": "Заметных путей в файловой системе нет.",
  "report.noDeps": "Встроенных зависимостей не обнаружено.",
  "report.obfNote": "Чем выше — тем сильнее обфускация. Само по себе не вредоносно.",
  "report.findings": "находки — {n}",
  "report.expandAll": "Развернуть всё",
  "report.collapseAll": "Свернуть всё",
  "report.all": "Все",
  "report.noFindings": "Находок нет.",
  "report.footer.static": "статический анализ — плагин не запускался",
  "report.footer.sandbox": "статический анализ + запуск в изолированной песочнице",
  "report.footer.line": "анализ занял {ms} мс · движок v{v} · {mode}",
  "report.gaugeLabel": "безопасность / 100",
  "report.outOf": "/ 100",

  // ── Finding card ────────────────────────────────────────────────────────
  "finding.location": "расположение",
  "finding.evidence": "улика",
  "finding.correlated": "связано",
  "finding.in": "в",
  "finding.recommendation": "Рекомендация —",
  "finding.pts": "−{n} б.",

  // ── Sandbox panel ───────────────────────────────────────────────────────
  "sandbox.title": "динамическая песочница",
  "sandbox.intro":
    "Плагин был запущен в изолированном контейнере без доступа к сети, а его реальное поведение записано. Это ловит действия, построенные через рефлексию или раскодированные на лету, которые статический анализ не видит.",
  "sandbox.running": "Запуск плагина в песочнице…",
  "sandbox.runningSuffix": "Эта страница обновляется автоматически.",
  "sandbox.inactive": "Динамический анализ не проводился.",
  "sandbox.clean":
    "В сработавших путях кода опасного поведения во время выполнения не замечено.",
  "sandbox.newMissed": "Новое — статика пропустила",
  "sandbox.confirms": "Подтверждает статику",
  "sandbox.blocked": "Заблокировано",
  "sandbox.trail": "Трасса поведения — событий: {n}",
  "sandbox.blockedLower": "заблокировано",
  "sandbox.caveatsSummary": "Что песочница может и чего не может доказать",
  "sandbox.recommendation": "Рекомендация —",

  // ── Authenticity (online provenance) panel ──────────────────────────────
  "provenance.title": "подлинность",
  "provenance.intro":
    "Этот файл был онлайн сверен с подлинным релизом из официальных источников (Modrinth, Hangar, GitHub). Это ловит копии популярных плагинов с бэкдором, которые раздают на ненадёжных сайтах.",
  "provenance.running": "Проверка официальных источников…",
  "provenance.runningSuffix": "Эта страница обновляется автоматически.",
  "provenanceStatus.DISABLED": "отключено",
  "provenanceStatus.PENDING": "в очереди",
  "provenanceStatus.RUNNING": "проверка",
  "provenanceStatus.VERIFIED": "подлинный",
  "provenanceStatus.TAMPERED": "подделка",
  "provenanceStatus.NOT_FOUND": "не найден",
  "provenanceStatus.UNVERIFIED": "не проверен",
  "provenanceStatus.SKIPPED": "пропущено",
  "provenanceStatus.FAILED": "ошибка",
  "provenance.verifiedTitle": "Подлинный официальный релиз",
  "provenance.verifiedBody":
    "Байты этого файла идентичны официальному релизу — это подлинная сборка, а не изменённая копия.",
  "provenance.tamperedTitle": "НЕ совпадает с официальным релизом",
  "provenance.tamperedBody":
    "Файл выдаёт себя за {name} {version}, но его байты отличаются от официального релиза на {source}. Изменённая копия известного плагина — серьёзный признак бэкдора.",
  "provenance.notFoundTitle": "Не удалось проверить",
  "provenance.notFoundBody":
    "{name} не найден ни в одном из проверенных официальных источников, поэтому подлинность подтвердить не удалось. Отсутствие совпадения не доказывает подделку.",
  "provenance.unverifiedBody":
    "Не найдено имени/версии плагина или ссылки на исходник, с которыми можно было бы сверить файл.",
  "provenance.project": "Проект",
  "provenance.version": "Версия",
  "provenance.source": "Источник",
  "provenance.officialFile": "Официальный файл",
  "provenance.openProject": "Открыть на {source}",
  "provenance.diffTitle": "Отличия от официальной сборки",
  "provenance.diffCounts": "официально классов: {o} · в этом файле: {u}",
  "provenance.diffAdded": "Добавлено — нет в официальной сборке ({n})",
  "provenance.diffModified": "Изменено ({n})",
  "provenance.diffRemoved": "Удалено ({n})",
  "provenance.diffInjected": "внедрено",
  "provenance.diffTruncated": "…и другие (список сокращён)",
  "provenance.sources": "Проверенные источники",
  "provenance.caveatsSummary": "Что эта проверка доказывает, а что нет",

  // ── Report client (loading / error) ─────────────────────────────────────
  "reportClient.loading": "Загрузка отчёта…",
  "reportClient.unavailable": "Отчёт недоступен",
  "reportClient.loadError": "Не удалось загрузить этот отчёт.",
  "reportClient.expire":
    "Отчёты хранятся в памяти и исчезают при перезапуске анализатора.",
  "reportClient.scanCta": "Проверить плагин",
  "api.unreachable": "Не удалось связаться с сервисом анализатора. Он запущен на {url}?",

  // ── Verdicts ────────────────────────────────────────────────────────────
  "verdict.MINIMAL_RISK": "Минимальный риск",
  "verdict.LOW_RISK": "Низкий риск",
  "verdict.MEDIUM_RISK": "Средний риск",
  "verdict.HIGH_RISK": "Высокий риск",
  "verdict.CRITICAL_RISK": "Критический риск",

  // ── Severities ──────────────────────────────────────────────────────────
  "severity.CRITICAL": "Критическая",
  "severity.HIGH": "Высокая",
  "severity.MEDIUM": "Средняя",
  "severity.LOW": "Низкая",
  "severity.INFO": "Инфо",
  "severityShort.CRITICAL": "Крит",
  "severityShort.HIGH": "Выс",
  "severityShort.MEDIUM": "Сред",
  "severityShort.LOW": "Низ",
  "severityShort.INFO": "Инфо",

  // ── Categories ──────────────────────────────────────────────────────────
  "category.STRUCTURE": "Структура",
  "category.PLUGIN_YML": "plugin.yml",
  "category.NETWORK": "Сеть",
  "category.PROCESS": "Процессы",
  "category.CLASS_LOADING": "Загрузка классов",
  "category.NATIVE": "Нативный код",
  "category.FILESYSTEM": "Файловая система",
  "category.CRYPTO": "Криптография",
  "category.REFLECTION": "Рефлексия",
  "category.SCRIPTING": "Скрипты",
  "category.DESERIALIZATION": "Десериализация",
  "category.SYSTEM": "Управление JVM",
  "category.OBFUSCATION": "Обфускация",
  "category.STRING_IOC": "Индикаторы",
  "category.SUPPLY_CHAIN": "Цепочка поставок",
  "category.COMBO": "Корреляция",
  "category.MINECRAFT": "Minecraft API",
  "category.MALWARE_SIGNATURE": "Известная малварь",
  "category.RESOURCE_PACK": "Ресурс-пак",
  "category.DATA_PACK": "Дата-пак",
  "category.PROVENANCE": "Происхождение",

  // ── Sandbox status ──────────────────────────────────────────────────────
  "sandboxStatus.DISABLED": "Отключена",
  "sandboxStatus.PENDING": "В очереди",
  "sandboxStatus.RUNNING": "Выполняется",
  "sandboxStatus.COMPLETED": "Завершена",
  "sandboxStatus.SKIPPED": "Пропущена",
  "sandboxStatus.UNAVAILABLE": "Недоступна",
  "sandboxStatus.FAILED": "Ошибка",

  // ── Behaviour types ─────────────────────────────────────────────────────
  "behavior.PROCESS_EXEC": "Запуск процесса",
  "behavior.DEFINE_CLASS": "Определение класса в рантайме",
  "behavior.LOAD_LIBRARY": "Загрузка нативной библиотеки",
  "behavior.JNDI_LOOKUP": "JNDI-запрос",
  "behavior.SECURITY_MANAGER": "Попытка выхода из песочницы",
  "behavior.DESERIALIZE": "Десериализация",
  "behavior.NETWORK_CONNECT": "Исходящее соединение",
  "behavior.NETWORK_LISTEN": "Прослушивающий сокет",
  "behavior.SCRIPTING": "Выполнение скрипта",
  "behavior.DNS_RESOLVE": "Разрешение DNS",
  "behavior.FILE_WRITE": "Запись в файловую систему",
  "behavior.FILE_READ": "Чтение файловой системы",
  "behavior.REFLECTION": "Рефлексия",
  "behavior.SET_PROPERTY": "Изменение системного свойства",
  "behavior.ENV_READ": "Чтение окружения",
  "behavior.OUTPUT": "Вывод",
  "behavior.LIFECYCLE": "Жизненный цикл",
  "behavior.ERROR": "Ошибка харнесса",
};

const MESSAGES: Record<Lang, Dict> = { en, ru };

export type TFunction = (key: string, vars?: Record<string, string | number>) => string;

interface I18nValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggle: () => void;
  t: TFunction;
}

const I18nContext = createContext<I18nValue | null>(null);

/** Default before client hydration; the effect below upgrades it from storage / browser. */
const DEFAULT_LANG: Lang = "ru";

function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    k in vars ? String(vars[k]) : `{${k}}`,
  );
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(DEFAULT_LANG);

  // On mount, prefer a stored choice, else the browser language.
  useEffect(() => {
    let initial: Lang = DEFAULT_LANG;
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored === "en" || stored === "ru") {
        initial = stored;
      } else if (typeof navigator !== "undefined") {
        initial = navigator.language.toLowerCase().startsWith("ru") ? "ru" : "en";
      }
    } catch {
      /* storage blocked — keep the default */
    }
    setLangState(initial);
  }, []);

  // Keep <html lang> in sync for accessibility and ::selection / scrollbar styling.
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = useCallback((next: Lang) => {
    setLangState(next);
    try {
      localStorage.setItem(STORAGE_KEY, next);
    } catch {
      /* ignore */
    }
  }, []);

  const toggle = useCallback(
    () => setLang(lang === "en" ? "ru" : "en"),
    [lang, setLang],
  );

  const t = useCallback<TFunction>(
    (key, vars) => {
      const table = MESSAGES[lang];
      const value = table[key] ?? MESSAGES.en[key] ?? key;
      return interpolate(value, vars);
    },
    [lang],
  );

  const value = useMemo<I18nValue>(
    () => ({ lang, setLang, toggle, t }),
    [lang, setLang, toggle, t],
  );

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue {
  const ctx = useContext(I18nContext);
  if (!ctx) {
    throw new Error("useI18n must be used within a LanguageProvider");
  }
  return ctx;
}
